export const detaCards = [
   {
      name: 'Item 1',
      href: '',
      NumStars: '1',
      originalProductValue: '200,00',
      productValue: '159,99',
      image: '',
   },
   {
      name: 'Item 2',
      href: '',
      NumStars: '5',
      originalProductValue: '500,00',
      productValue: '400,00',
      image: '',
   },
   {
      name: 'Item 3',
      href: '',
      NumStars: '3',
      originalProductValue: '3000,00',
      productValue: '2799,99',
      image: '',
   },
   {
      name: 'Item 4',
      href: '',
      NumStars: '1',
      originalProductValue: '19,00',
      productValue: '16,00',
      image: '',
   },
   {
      name: 'Item 5',
      href: '',
      NumStars: '4',
      originalProductValue: '50,00',
      productValue: '32,00',
      image: '',
   },
   {
      name: 'Item 6',
      href: '',
      NumStars: '3',
      originalProductValue: '15,00',
      productValue: '10,00',
      image: '',
   },
   {
      name: 'Item 7',
      href: '',
      NumStars: '5',
      originalProductValue: '1.600,00',
      productValue: '1.300,00',
      image: '',
   },
   {
      name: 'Item 8',
      href: '',
      NumStars: '4',
      originalProductValue: '50,00',
      productValue: '33,00',
      image: '',
   },
   {
      name: 'Item 9',
      href: '',
      NumStars: '4',
      originalProductValue: '50,00',
      productValue: '32,99',
      image: '',
   },
   {
      name: 'Item 10',
      href: '',
      NumStars: '3',
      originalProductValue: '20,00',
      productValue: '14,99',
      image: '',
   },
   {
      name: 'Item 11',
      href: '',
      NumStars: '5',
      originalProductValue: '160,00',
      productValue: '139,99',
      image: '',
   },
   {
      name: 'Item 12',
      href: '',
      NumStars: '',
      originalProductValue: '100,00',
      productValue: '99,99',
      image: '',
   },
]
