export const infoCards = [
   {
      img: './imgs/des01.png',
      title: 'Desafio01',
      nameChall: 'Criar repositorio ',
      description: 'Criar o repositório para manter os projetos.',
   },
   {
      img: './imgs/des02.png',
      title: 'Desafio02',
      href: 'https://desafio02-ting.netlify.app',
      nameChall: 'óla mundo',
      description: 'Criar um Hello World customizado com fontes, cores e imagens.',
   },
   {
      img: './imgs/des03.png',
      title: 'Desafio03',
      nameChall: ' Botão animado',
      href: 'https://desafio03-xi.vercel.app/',
      description: 'Criar um botão animado.',
   },
   {
      img: './imgs/des04.png',
      title: 'Desafio04',
      nameChall: 'Calculadora',
      href: 'https://desafio04-coral.vercel.app/',
      description: 'Criar uma calculadora .',
   },

   {
      img: './imgs/des05.avif',
      title: 'Desafio05',
      nameChall: 'Página 404',
      description: 'Criar uma página personalizada do error 404 "Não encontrado."',
      href: 'https://desafio05-ting.netlify.app',
   },
   {
      img: './imgs/des06.avif',
      title: 'Desafio06',
      nameChall: 'Glassmorphism',
      description: 'Criar uma pagina que tenha o efeito de vidro mas conhecido como Glassmorphism.',
      href: 'https://desafio06-ting.netlify.app',
   },
   { img: './imgs/des07.avif', title: 'Desafio07', nameChall: 'Contador', description: 'Desenvolver um contador.', href: 'https://desafio07-ting.netlify.app' },
   {
      img: './imgs/des08.avif',
      title: 'Desafio08',
      nameChall: 'Toggle mode',
      description: 'Crie um toggle para alternar do modo escuro para o claro.',
      href: 'https://desafio08-ting.netlify.app',
   },
   {
      img: './imgs/des09.avif',
      title: 'Desafio09',
      nameChall: 'Barra de load',
      description: 'Criar um load com animação fluida',
      href: 'https://desafio09-ting.netlify.app',
   },
   {
      img: './imgs/des10.png',
      title: 'Desafio10',
      nameChall: 'API ParticlasJS',
      description: 'Use a biblioteca ParticleJS para construir um projeto com particulas animadas.',
      href: 'https://21dias-de-codigo-rocketseat.vercel.app/',
   },
   {
      img: './imgs/des11.avif',
      title: 'Desafio11',
      nameChall: 'Formulario',
      description: 'Criar uma pagina de cadastro.',
      href: 'https://desafio11-ting.netlify.app',
   },
   { img: './imgs/des12.avif', title: 'Desafio12', nameChall: 'Galeria', description: 'Galeria de imagens.', href: 'https://desafio12-ting.netlify.app' },
   {
      img: './imgs/des13.avif',
      title: 'Desafio13',
      nameChall: 'Menu responsivo',
      description: 'Crie um menu responsivo.',
      href: 'https://desafio13-ting.netlify.app',
   },
   {
      img: './imgs/des14.avif',
      title: 'Desafio14',
      nameChall: 'Quiz',
      description: 'Desenvolver o leiaute de um quiz',
      href: 'https://desafio14-ting.netlify.app',
   },
   {
      img: './imgs/des15.avif',
      title: 'Desafio15',
      nameChall: 'Vitrine  e-commerce ',
      description: 'Crie uma vitrine de um e-commerce ficticio com : nome dos produtos , preço e imagen.',
      href: 'https://desafio15-ting.netlify.app',
   },
   {
      img: './imgs/des16.avif',
      title: 'Desafio16',
      nameChall: 'Site com API publica',
      description: 'Desenvolver um site consumindo uma API pública.',
      href: 'https://desafio16-ting.netlify.app',
   },
   {
      img: './imgs/des17.avif',
      title: 'Desafio17',
      nameChall: 'Captura dos cliques do teclado',
      description: 'projeto que capture os cliques do teclado.',
      href: 'https://desafio17-ting.netlify.app',
   },
   {
      img: './imgs/des18.avif',
      title: 'Desafio18',
      nameChall: 'Gerador de senhas aleatorias',
      description: 'Desenvolver um gerador de senhas aleatorias.',
      href: 'https://desafio18-ting.netlify.app',
   },
   {
      img: './imgs/des19.avif',
      title: 'Desafio19',
      nameChall: 'Site com a API do Unsplash',
      description: 'Desenvolver um site que consuma a API do Unsplash.',
      href: 'https://desafio19-ting.netlify.app',
   },
   {
      img: './imgs/des20.avif',
      title: 'Desafio20',
      nameChall: 'Emoje picke',
      description: 'Emoje picke que exibe emojis que podem ser copiados para a área de transferência',
      href: 'https://desafio20-ting.netlify.app',
   },
   {
      img: './imgs/des21.avif',
      title: 'Desafio21',
      nameChall: 'Portfólio com os desafios',
      description: 'Desenvolver pagina para ser o seu portfólio com os projetos codados durante os 21 dias.',
      href: 'https://desafio21-ting.netlify.app',
   },
]
